spring:
  application:
    name: conductor-boot-wrapper
  datasource:
    name: conductor
    username: Conductor
    password: Conductor!23$
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10000
      maxLifetime: 5000
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
## QuartzProperties
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 1000
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: ${spring.application.name}

server:
  port: 8080

logging:
  level:
    root: info

awaitTermination: 300

logbook:
  filter:
    enabled: true
  write:
    level: info
    chunk-size: 10000
  format:
    style: splunk
  exclude: [/actuator/**, /v3/api-docs/**, /swagger-ui/**, /index.html, /api/swagger.json]
  strategy: body-only-if-status-at-least
  minimum-status: 400

wrapper_db: mariadb4j

# For PERSISTENT data - use dataDir property
mariadb4j:
  database:
    name: ${spring.datasource.name}
  port: 3306
  dataDir: ${spring.application.name}-data
  libDir: ${spring.application.name}-lib
  baseDir: ${spring.application.name}-base
#  dataDir: /appln/db/${spring.application.name}-data
#  libDir: /appln/db/${spring.application.name}-lib
#  baseDir: /appln/db/${spring.application.name}-base
  maxConnections: 10000
  wait: 
    timeout: 18000000
  connect:
    timeout: 31536000
  deleteBaseAndDataDirOnShutdown: false
  security:
    disabled: true

## Conductor MYSQL Configuration for Hikari DataSource
db: mysql
jdbc:
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}  
conductor:
  server:
    api:
      url: http://localhost:${conductor.jetty.server.port}/api/
  jetty:
    server:
      port: 1987
  mysql:
    connection:
      timeout: 18000000
      idle:
        timeout: 31536000 
      pool:
        idle:
          min: 2
        size:
          max: 10000

zuul:
  add-proxy-headers: true
  add-host-header: true
  ssl-hostname-validation-enabled: false
  routes:
    conductor-index:
      path: /
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
    conductor-html:
      path: /index.html
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-json:
      path: /api/swagger.json
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-lib:
      path: /lib/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-css:
      path: /css/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-swagger-js:
      path: /swagger-ui.js
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false
    conductor-api:
      path: /api/**
      url: http://localhost:${conductor.jetty.server.port}
      retryable: true
      strip-prefix: false